### ISSUE TITLE
can you add an option for snyk?

### ISSUE THREAD

**Issue by iot-resister** [keytelematics/gitlab-ci-yarn-audit-parser#4]
Here's an example 
```yml
# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.
version: v1.14.1
# ignores vulnerabilities until expiry date; change duration by modifying expiry date
ignore:
  SNYK-JS-NODEFETCH-674311:
    - graphql-tools > @graphql-tools/relay-operation-optimizer > relay-compiler > fbjs > isomorphic-fetch > node-fetch:
        reason: None given
        expires: '2020-12-11T17:52:54.659Z'
    - graphql-tools > @graphql-tools/relay-operation-optimizer > relay-compiler > relay-runtime > fbjs > isomorphic-fetch > node-fetch:
        reason: None available
        expires: '2020-12-11T17:52:54.659Z'
patch: {}

````

@leon0399
